theme: jekyll-theme-merlot
# Google Analytics
google_analytics: G-PZCQMDKHT6
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-PZCQMDKHT6"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-PZCQMDKHT6');
</script>
